/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import student.Student;
import student.Class;

/**
 *
 * @author ADMIN
 */
public class Home extends javax.swing.JFrame {

    Student student = new Student();
    private int x_key, y_key;
    private DefaultTableModel model;
    private int rowIndex;
    Class stu_class = new Class();
    Mark stu_mark = new Mark();

    public Home() {
        initComponents();
        init();
    }

    public void init() {
        viewTable_student();
        ipt_studentID.setText(String.valueOf(student.getMax()));
    }

    public void viewTable_student() {
        student.getStudentInfo(student_info_table, "");
        model = (DefaultTableModel) student_info_table.getModel();
        model.fireTableDataChanged();
        student_info_table.setRowHeight(30);
        student_info_table.setShowGrid(true);
        student_info_table.setGridColor(Color.black);
        student_info_table.setBackground(Color.white);
    }

    // Nut clear ben sheet Students
    public void clear_student_info() {
        ipt_studentID.setText(String.valueOf(student.getMax()));
        ipt_maSV.setText("");
        ipt_studentName.setText("");
        chose_dateOfBirth.setDate(null);
        compb_gender.setSelectedIndex(0);
        ipt_studentPhoneNumber.setText("");
        ipt_studentEmail.setText("");
        ipt_studentAddress.setText("");
    }

    public boolean isEmptyStudent() {
        if (ipt_studentName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is missing");
            return false;
        }
        if (chose_dateOfBirth.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Day of birth is missing");
            return false;
        }
        if (chose_dateOfBirth.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(this, "There ain't be no time traveller");
            return false;
        }
        if (ipt_studentPhoneNumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone number is missing");
            return false;
        }
        if (ipt_studentPhoneNumber.getText().length() != 10) {
            JOptionPane.showMessageDialog(this, "Invalid phone number");
            return false;
        }
        if (!ipt_studentEmail.getText().matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")) {
            JOptionPane.showMessageDialog(this, "Invalid email address");
            return false;
        }
        if (ipt_studentAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address is missing");
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ipt_3 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        tab_student = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        ipt_studentEmail = new javax.swing.JTextField();
        ipt_studentID = new javax.swing.JTextField();
        ipt_studentName = new javax.swing.JTextField();
        ipt_studentPhoneNumber = new javax.swing.JTextField();
        ipt_studentAddress = new javax.swing.JTextField();
        compb_gender = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        Gender1 = new javax.swing.JLabel();
        Gender4 = new javax.swing.JLabel();
        Gender5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btn_addStudent = new javax.swing.JButton();
        btn_updateStudetn = new javax.swing.JButton();
        btn_clearStudentInfo = new javax.swing.JButton();
        chose_dateOfBirth = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        ipt_maSV = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        search_student_for_info = new javax.swing.JTextField();
        btn_find_student_for_info = new javax.swing.JButton();
        btn_clearSearch = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        student_info_table = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btn_deleteStudent = new javax.swing.JButton();
        btn_clearStudent_onTable = new javax.swing.JButton();
        btn_show_all_students = new javax.swing.JButton();
        btn_print_students = new javax.swing.JButton();
        jPanel39 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        search_student_for_class = new javax.swing.JTextField();
        btn_find_student_for_class = new javax.swing.JButton();
        btn_clearID__class = new javax.swing.JButton();
        jPanel38 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        class_info_table = new javax.swing.JTable();
        jPanel37 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        opt_studentName__class = new javax.swing.JTextField();
        opt_totalCredits__class = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_printClasses = new javax.swing.JButton();
        btn_clearClass_onTable__class = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        search_student_for_mark = new javax.swing.JTextField();
        btn_find_student_for_mark = new javax.swing.JButton();
        btn_clearID__mark = new javax.swing.JButton();
        jPanel46 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        mark_info_table = new javax.swing.JTable();
        jPanel47 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        opt_studentName__mark = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        compb_SearchSchoolyear = new javax.swing.JComboBox<>();
        compb_SearchSemester = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        btn_showMark = new javax.swing.JButton();
        btn_clearClass_onTable__class2 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        opt_totalScore = new javax.swing.JTextField();
        btn_printClasses2 = new javax.swing.JButton();

        ipt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipt_3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 70));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setText("STUDENT MANAGEMENT SYSTEM - KIT");

        btn_logout.setBackground(new java.awt.Color(255, 204, 153));
        btn_logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_logout.setText("Log out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_exit.setBackground(new java.awt.Color(255, 153, 153));
        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_logout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );

        tab_student.setBackground(new java.awt.Color(153, 204, 255));
        tab_student.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tab_student.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tab_studentFocusGained(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 204, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        ipt_studentEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipt_studentEmailActionPerformed(evt);
            }
        });

        ipt_studentID.setEditable(false);
        ipt_studentID.setBackground(new java.awt.Color(204, 204, 204));
        ipt_studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipt_studentIDActionPerformed(evt);
            }
        });

        ipt_studentPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ipt_studentPhoneNumberKeyTyped(evt);
            }
        });

        compb_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("No.");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Date of birth:");

        Gender.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Gender.setText("Gender:");

        Gender1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Gender1.setText("Phone Number:");

        Gender4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Gender4.setText("Email:");

        Gender5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Gender5.setText("Address:");

        jPanel9.setBackground(new java.awt.Color(153, 204, 255));
        jPanel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        btn_addStudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_addStudent.setText("Add Student");
        btn_addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addStudentActionPerformed(evt);
            }
        });

        btn_updateStudetn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_updateStudetn.setText("Update ");
        btn_updateStudetn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateStudetnActionPerformed(evt);
            }
        });

        btn_clearStudentInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clearStudentInfo.setText("Clear");
        btn_clearStudentInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearStudentInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btn_addStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_updateStudetn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btn_clearStudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_updateStudetn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clearStudentInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        chose_dateOfBirth.setDateFormatString("dd-MM-yyyy");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Student ID");

        ipt_maSV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ipt_maSVFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Gender)
                                    .addComponent(Gender1)
                                    .addComponent(Gender4)
                                    .addComponent(Gender5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(compb_gender, 0, 177, Short.MAX_VALUE)
                                        .addComponent(ipt_studentPhoneNumber))
                                    .addComponent(ipt_studentEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                    .addComponent(ipt_studentAddress)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ipt_maSV)
                                            .addComponent(ipt_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(chose_dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 56, Short.MAX_VALUE))
                                    .addComponent(ipt_studentName))))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ipt_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(ipt_maSV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ipt_studentName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chose_dateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(compb_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ipt_studentPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ipt_studentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ipt_studentAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 2));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Search Students by ID:");

        search_student_for_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_student_for_infoActionPerformed(evt);
            }
        });
        search_student_for_info.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_student_for_infoKeyTyped(evt);
            }
        });

        btn_find_student_for_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_18px_1.png"))); // NOI18N
        btn_find_student_for_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_find_student_for_infoActionPerformed(evt);
            }
        });

        btn_clearSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_clear_symbol_18px_2.png"))); // NOI18N
        btn_clearSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_student_for_info, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_find_student_for_info, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_clearSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(search_student_for_info, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_find_student_for_info, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        student_info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Student ID", "Name", "Date of birth", "Gender", "Phone number", "Email", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student_info_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                student_info_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(student_info_table);
        if (student_info_table.getColumnModel().getColumnCount() > 0) {
            student_info_table.getColumnModel().getColumn(0).setMinWidth(20);
            student_info_table.getColumnModel().getColumn(0).setPreferredWidth(30);
            student_info_table.getColumnModel().getColumn(0).setMaxWidth(30);
            student_info_table.getColumnModel().getColumn(1).setMinWidth(90);
            student_info_table.getColumnModel().getColumn(1).setPreferredWidth(90);
            student_info_table.getColumnModel().getColumn(1).setMaxWidth(90);
            student_info_table.getColumnModel().getColumn(2).setMinWidth(100);
            student_info_table.getColumnModel().getColumn(2).setPreferredWidth(130);
            student_info_table.getColumnModel().getColumn(2).setMaxWidth(130);
            student_info_table.getColumnModel().getColumn(3).setMinWidth(70);
            student_info_table.getColumnModel().getColumn(3).setPreferredWidth(80);
            student_info_table.getColumnModel().getColumn(3).setMaxWidth(80);
            student_info_table.getColumnModel().getColumn(4).setMinWidth(50);
            student_info_table.getColumnModel().getColumn(4).setPreferredWidth(70);
            student_info_table.getColumnModel().getColumn(4).setMaxWidth(70);
            student_info_table.getColumnModel().getColumn(5).setMinWidth(70);
            student_info_table.getColumnModel().getColumn(5).setPreferredWidth(90);
            student_info_table.getColumnModel().getColumn(5).setMaxWidth(90);
            student_info_table.getColumnModel().getColumn(6).setMinWidth(90);
            student_info_table.getColumnModel().getColumn(6).setPreferredWidth(200);
            student_info_table.getColumnModel().getColumn(6).setMaxWidth(200);
            student_info_table.getColumnModel().getColumn(7).setPreferredWidth(180);
        }

        jPanel8.setBackground(new java.awt.Color(153, 204, 255));

        btn_deleteStudent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_deleteStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_delete_18px.png"))); // NOI18N
        btn_deleteStudent.setText("Delete Student");
        btn_deleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteStudentActionPerformed(evt);
            }
        });

        btn_clearStudent_onTable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clearStudent_onTable.setText("Clear");
        btn_clearStudent_onTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearStudent_onTableActionPerformed(evt);
            }
        });

        btn_show_all_students.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_show_all_students.setText("Show all");
        btn_show_all_students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_show_all_studentsActionPerformed(evt);
            }
        });

        btn_print_students.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_print_students.setText("Print");
        btn_print_students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_print_studentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btn_print_students)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_show_all_students)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_clearStudent_onTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_deleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_deleteStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clearStudent_onTable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_show_all_students, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_print_students, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 896, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_student.addTab("STUDENTS", jPanel3);

        jPanel39.setBackground(new java.awt.Color(153, 204, 255));

        jPanel36.setBackground(new java.awt.Color(153, 204, 255));
        jPanel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 2));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("Search Students by ID:");

        search_student_for_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_student_for_classActionPerformed(evt);
            }
        });
        search_student_for_class.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_student_for_classKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_student_for_classKeyTyped(evt);
            }
        });

        btn_find_student_for_class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_18px_1.png"))); // NOI18N
        btn_find_student_for_class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_find_student_for_classActionPerformed(evt);
            }
        });

        btn_clearID__class.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_delete_18px.png"))); // NOI18N
        btn_clearID__class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearID__classActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_student_for_class, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_find_student_for_class, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clearID__class, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel36Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_clearID__class, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel29)
                        .addComponent(search_student_for_class, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_find_student_for_class, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel38.setBackground(new java.awt.Color(153, 204, 255));
        jPanel38.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        class_info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester", "Schoo  Year", "Credits", "Class name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(class_info_table);
        if (class_info_table.getColumnModel().getColumnCount() > 0) {
            class_info_table.getColumnModel().getColumn(0).setMinWidth(90);
            class_info_table.getColumnModel().getColumn(0).setPreferredWidth(90);
            class_info_table.getColumnModel().getColumn(0).setMaxWidth(90);
            class_info_table.getColumnModel().getColumn(1).setMinWidth(120);
            class_info_table.getColumnModel().getColumn(1).setPreferredWidth(120);
            class_info_table.getColumnModel().getColumn(1).setMaxWidth(120);
            class_info_table.getColumnModel().getColumn(2).setMinWidth(90);
            class_info_table.getColumnModel().getColumn(2).setPreferredWidth(90);
            class_info_table.getColumnModel().getColumn(2).setMaxWidth(90);
        }

        jPanel37.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1266, Short.MAX_VALUE)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Student's name:");

        opt_studentName__class.setEditable(false);
        opt_studentName__class.setBackground(new java.awt.Color(204, 204, 204));

        opt_totalCredits__class.setEditable(false);
        opt_totalCredits__class.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Total credits:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opt_studentName__class)
                    .addComponent(opt_totalCredits__class)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 229, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt_studentName__class, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt_totalCredits__class, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_printClasses.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_printClasses.setText("Print");
        btn_printClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printClassesActionPerformed(evt);
            }
        });

        btn_clearClass_onTable__class.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clearClass_onTable__class.setText("Clear");
        btn_clearClass_onTable__class.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearClass_onTable__classActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(jPanel38);
        jPanel38.setLayout(jPanel38Layout);
        jPanel38Layout.setHorizontalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel38Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_printClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_clearClass_onTable__class, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE))
                    .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel38Layout.setVerticalGroup(
            jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel38Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel38Layout.createSequentialGroup()
                        .addComponent(btn_printClasses, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clearClass_onTable__class, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(jPanel39);
        jPanel39.setLayout(jPanel39Layout);
        jPanel39Layout.setHorizontalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel39Layout.createSequentialGroup()
                        .addComponent(jPanel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel39Layout.setVerticalGroup(
            jPanel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel39Layout.createSequentialGroup()
                .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_student.addTab("CLASSES", jPanel39);

        jPanel30.setBackground(new java.awt.Color(153, 204, 255));

        jPanel43.setBackground(new java.awt.Color(153, 204, 255));
        jPanel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 2));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel31.setText("Search Students by ID:");

        search_student_for_mark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_student_for_markActionPerformed(evt);
            }
        });
        search_student_for_mark.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                search_student_for_markKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                search_student_for_markKeyTyped(evt);
            }
        });

        btn_find_student_for_mark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_18px_1.png"))); // NOI18N
        btn_find_student_for_mark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_find_student_for_markActionPerformed(evt);
            }
        });

        btn_clearID__mark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_delete_18px.png"))); // NOI18N
        btn_clearID__mark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearID__markActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_student_for_mark, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_find_student_for_mark, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clearID__mark, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel43Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_clearID__mark, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel31)
                        .addComponent(search_student_for_mark, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_find_student_for_mark, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel46.setBackground(new java.awt.Color(153, 204, 255));
        jPanel46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        mark_info_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semester", "School  Year", "Mark", "ClassID", "Credits", "Class name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(mark_info_table);
        if (mark_info_table.getColumnModel().getColumnCount() > 0) {
            mark_info_table.getColumnModel().getColumn(0).setMinWidth(90);
            mark_info_table.getColumnModel().getColumn(0).setPreferredWidth(90);
            mark_info_table.getColumnModel().getColumn(0).setMaxWidth(90);
            mark_info_table.getColumnModel().getColumn(1).setMinWidth(120);
            mark_info_table.getColumnModel().getColumn(1).setPreferredWidth(120);
            mark_info_table.getColumnModel().getColumn(1).setMaxWidth(120);
            mark_info_table.getColumnModel().getColumn(2).setMinWidth(90);
            mark_info_table.getColumnModel().getColumn(2).setPreferredWidth(90);
            mark_info_table.getColumnModel().getColumn(2).setMaxWidth(90);
            mark_info_table.getColumnModel().getColumn(3).setMinWidth(90);
            mark_info_table.getColumnModel().getColumn(3).setPreferredWidth(90);
            mark_info_table.getColumnModel().getColumn(3).setMaxWidth(90);
            mark_info_table.getColumnModel().getColumn(4).setMinWidth(90);
            mark_info_table.getColumnModel().getColumn(4).setPreferredWidth(90);
            mark_info_table.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        jPanel47.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jPanel47Layout = new javax.swing.GroupLayout(jPanel47);
        jPanel47.setLayout(jPanel47Layout);
        jPanel47Layout.setHorizontalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1188, Short.MAX_VALUE)
        );
        jPanel47Layout.setVerticalGroup(
            jPanel47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(153, 204, 255));
        jPanel12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 153, 255), 2, true));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Student's name:");

        opt_studentName__mark.setEditable(false);
        opt_studentName__mark.setBackground(new java.awt.Color(204, 204, 204));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("School Year");

        compb_SearchSchoolyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020-2021", "2021-2022", "2022-2023", "2023-2024" }));

        compb_SearchSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "hè" }));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel35.setText("Semester");

        btn_showMark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_showMark.setText("Show");
        btn_showMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showMarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(opt_studentName__mark, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(compb_SearchSchoolyear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel12Layout.createSequentialGroup()
                                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(compb_SearchSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGap(0, 112, Short.MAX_VALUE)
                        .addComponent(btn_showMark, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opt_studentName__mark, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compb_SearchSchoolyear, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(compb_SearchSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(btn_showMark, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        btn_clearClass_onTable__class2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clearClass_onTable__class2.setText("Clear");
        btn_clearClass_onTable__class2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearClass_onTable__class2ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setText("Total Score:");

        opt_totalScore.setEditable(false);
        opt_totalScore.setBackground(new java.awt.Color(255, 255, 255));
        opt_totalScore.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_printClasses2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_printClasses2.setText("Print");
        btn_printClasses2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printClasses2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel46Layout = new javax.swing.GroupLayout(jPanel46);
        jPanel46.setLayout(jPanel46Layout);
        jPanel46Layout.setHorizontalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel46Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_printClasses2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(btn_clearClass_onTable__class2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opt_totalScore))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE))
                    .addGroup(jPanel46Layout.createSequentialGroup()
                        .addComponent(jPanel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(78, 78, 78)))
                .addContainerGap())
        );
        jPanel46Layout.setVerticalGroup(
            jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel46Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel46Layout.createSequentialGroup()
                        .addComponent(btn_printClasses2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_clearClass_onTable__class2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(opt_totalScore, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel30Layout.createSequentialGroup()
                        .addComponent(jPanel46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel30Layout.createSequentialGroup()
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tab_student.addTab("MARK", jPanel30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab_student)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1288, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab_student, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ipt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipt_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipt_3ActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        dispose();
        Login log_page = new Login();
        log_page.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Do you wanr to exit?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_exitActionPerformed
    // Chuot keo cua so
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x, y;
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();
        this.setLocation(x - x_key, y - y_key);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x_key = evt.getX();
        y_key = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed
    // Hieu ung khi mo ung dung
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.1; i <= 1; i += 0.1) {
            this.setOpacity((float) i);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btn_print_studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_print_studentsActionPerformed
        try {
            MessageFormat header = new MessageFormat("Student Information");
            MessageFormat footer = new MessageFormat("Page{0,number,integer}");
            student_info_table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_print_studentsActionPerformed

    private void btn_show_all_studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_show_all_studentsActionPerformed
        student_info_table.setModel(new DefaultTableModel(null, new Object[]{"Student ID", "Name", "Date of birth", "Gender", "Phone number", "Email", "Address"}));
        student.getStudentInfo(student_info_table, "");
    }//GEN-LAST:event_btn_show_all_studentsActionPerformed

    private void btn_clearStudent_onTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearStudent_onTableActionPerformed
        student_info_table.setModel(new DefaultTableModel(null, new Object[]{"Student ID", "Name", "Date of birth", "Gender", "Phone number", "Email", "Address"}));
    }//GEN-LAST:event_btn_clearStudent_onTableActionPerformed

    private void btn_deleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteStudentActionPerformed
        int id = Integer.parseInt(ipt_studentID.getText());
        if (student.isIdExist(id)) {
            // thuc hien xoa
            student.deleteStudentInfo(id);
            student_info_table.setModel(new DefaultTableModel(null, new Object[]{"Student ID", "Name", "Date of birth", "Gender", "Phone number", "Email", "Address"}));
            student.getStudentInfo(student_info_table, "");
            clear_student_info();
        } else {
            JOptionPane.showMessageDialog(this, "Studentt's id not found");
        }
    }//GEN-LAST:event_btn_deleteStudentActionPerformed

    private void student_info_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_student_info_tableMouseClicked
        model = (DefaultTableModel) student_info_table.getModel();
        rowIndex = student_info_table.getSelectedRow();
        ipt_studentID.setText(model.getValueAt(rowIndex, 0).toString());
        ipt_maSV.setText(model.getValueAt(rowIndex, 1).toString());
        ipt_studentName.setText(model.getValueAt(rowIndex, 2).toString());
        Date date;
        try {
            date = new SimpleDateFormat("dd-MM-yyyy").parse(model.getValueAt(rowIndex, 3).toString());
            chose_dateOfBirth.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        String gender = model.getValueAt(rowIndex, 4).toString();
        if (gender.equals("Male")) {
            compb_gender.setSelectedIndex(0);
        } else if (gender.equals("Female")) {
            compb_gender.setSelectedIndex(1);
        }
        ipt_studentPhoneNumber.setText(model.getValueAt(rowIndex, 5).toString());
        ipt_studentEmail.setText(model.getValueAt(rowIndex, 6).toString());
        ipt_studentAddress.setText(model.getValueAt(rowIndex, 7).toString());
    }//GEN-LAST:event_student_info_tableMouseClicked

    private void btn_clearSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearSearchActionPerformed
        search_student_for_info.setText("");
    }//GEN-LAST:event_btn_clearSearchActionPerformed

    // search student by id
    private void btn_find_student_for_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_find_student_for_infoActionPerformed
        if (search_student_for_info.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Must enter student's id");
        } else {
            String maSV = search_student_for_info.getText().toString();
            if (student.check_maSV(maSV)) {
                student_info_table.setModel(new DefaultTableModel(null, new Object[]{"Student ID", "Name", "Date of birth", "Gender", "Phone number", "Email", "Address"}));
                student.getStudentInfo_by_maSV(student_info_table, maSV);
            } else {
                JOptionPane.showMessageDialog(this, "Id does not exist");
                search_student_for_info.requestFocus();
            }
        }
    }//GEN-LAST:event_btn_find_student_for_infoActionPerformed

    private void search_student_for_infoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_student_for_infoKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != 'B' && evt.getKeyChar() != 'b') {
            evt.consume();
        }
    }//GEN-LAST:event_search_student_for_infoKeyTyped

    private void search_student_for_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_student_for_infoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_student_for_infoActionPerformed

    private void btn_clearStudentInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearStudentInfoActionPerformed
        clear_student_info();
    }//GEN-LAST:event_btn_clearStudentInfoActionPerformed

    private void btn_updateStudetnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateStudetnActionPerformed
        if (isEmptyStudent() && check_phoneNumber_exist() && check_email_exist() && check_maSV_exist()) {
            int id = Integer.parseInt(ipt_studentID.getText());
            String maSV = new String(ipt_maSV.getText());
            String name = new String(ipt_studentName.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String date_of_birth = sdf.format(chose_dateOfBirth.getDate());
            String gender = compb_gender.getSelectedItem().toString();
            String phoneNumber = new String(ipt_studentPhoneNumber.getText());
            String email = new String(ipt_studentEmail.getText());
            String address = new String(ipt_studentAddress.getText());
            if (id < student.getMax()) {
                student.update(id, maSV, name, date_of_birth, gender, phoneNumber, email, address);
                student_info_table.setModel(new DefaultTableModel(null, new Object[]{"No.", "Student ID", "Name", "Date of birth", "Gender", "Phone number", "Email", "Address"}));
                student.getStudentInfo(student_info_table, "");
                clear_student_info();
            } else {
                JOptionPane.showMessageDialog(this, "Student has not been added, could not update");
                return;
            }
        }
    }//GEN-LAST:event_btn_updateStudetnActionPerformed

    private void btn_addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addStudentActionPerformed
        if (isEmptyStudent()) { //true la ko rong ---> hop le
            if (check_phoneNumber_exist() && check_email_exist() && check_ID_exist() && check_maSV_exist()) {
                int id = student.getMax();
                String maSV = new String(ipt_maSV.getText());
                String name = new String(ipt_studentName.getText());
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
                String date_of_birth = dateFormat.format(chose_dateOfBirth.getDate());
                String gender = compb_gender.getSelectedItem().toString();
                String phoneNumber = new String(ipt_studentPhoneNumber.getText());
                String email = new String(ipt_studentEmail.getText());
                String address = new String(ipt_studentAddress.getText());
                student.insert(id, maSV, name, date_of_birth, gender, phoneNumber, email, address);
                // reset lai bang moi khi them sinh vien moi
                student_info_table.setModel(new DefaultTableModel(null, new Object[]{"No.", "Student ID", "Name", "Date of birth", "Gender", "Phone number", "Email", "Address"}));
                student.getStudentInfo(student_info_table, "");
                clear_student_info();
            }
        }
    }//GEN-LAST:event_btn_addStudentActionPerformed

    // cho phep nhap so, ko cho nhap chu vao o so dien thoai
    private void ipt_studentPhoneNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipt_studentPhoneNumberKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_ipt_studentPhoneNumberKeyTyped

    private void ipt_studentEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipt_studentEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipt_studentEmailActionPerformed

    private void btn_find_student_for_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_find_student_for_classActionPerformed
        if (search_student_for_class.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Type ID first");
        } else {
            String maSV = search_student_for_class.getText().toString();
            if (student.check_maSV(maSV)) {
                class_info_table.setModel(new DefaultTableModel(null, new Object[]{"Semester", "School Year", "Credit", "Class name"}));
                stu_class.get_class_by_stuID(class_info_table, maSV);
                opt_studentName__class.setText(student.getStudentName_bymaSV(maSV));
                opt_totalCredits__class.setText(Integer.toString(student.sum_credit(maSV)));
            } else {
                JOptionPane.showMessageDialog(this, "Id does not exist");
                search_student_for_class.requestFocus();
            }
        }
    }//GEN-LAST:event_btn_find_student_for_classActionPerformed

    private void search_student_for_classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_student_for_classActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_student_for_classActionPerformed

    private void search_student_for_classKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_student_for_classKeyTyped
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != 'B' && evt.getKeyChar() != 'b') {
            evt.consume();
        }
    }//GEN-LAST:event_search_student_for_classKeyTyped

    private void btn_clearID__classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearID__classActionPerformed
        search_student_for_class.setText("");
        opt_studentName__class.setText("");
        opt_totalCredits__class.setText("");
    }//GEN-LAST:event_btn_clearID__classActionPerformed

    private void ipt_studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipt_studentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ipt_studentIDActionPerformed

    private void ipt_maSVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ipt_maSVFocusGained

    }//GEN-LAST:event_ipt_maSVFocusGained

    private void tab_studentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tab_studentFocusGained
    }//GEN-LAST:event_tab_studentFocusGained

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
    }//GEN-LAST:event_jPanel3FocusGained

    private void search_student_for_classKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_student_for_classKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // thuc hien tim danh sach lop hoc bang phim ENTER
            if (search_student_for_class.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Type ID first");
            } else {
                String maSV = search_student_for_class.getText().toString();
                if (student.check_maSV(maSV)) {
                    class_info_table.setModel(new DefaultTableModel(null, new Object[]{"Semester", "School Year", "Credit", "Class name"}));
                    stu_class.get_class_by_stuID(class_info_table, maSV);
                    opt_studentName__class.setText(student.getStudentName_bymaSV(maSV));
                    opt_totalCredits__class.setText(Integer.toString(student.sum_credit(maSV)));
                } else {
                    JOptionPane.showMessageDialog(this, "Id does not exist");
                    search_student_for_class.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_search_student_for_classKeyReleased

    private void btn_clearClass_onTable__classActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearClass_onTable__classActionPerformed
        class_info_table.setModel(new DefaultTableModel(null, new Object[]{"Student ID", "Name", "Date of birth", "Gender", "Phone number", "Email", "Address"}));
    }//GEN-LAST:event_btn_clearClass_onTable__classActionPerformed

    private void btn_printClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printClassesActionPerformed
        try {
            MessageFormat header = new MessageFormat("Classes");
            MessageFormat footer = new MessageFormat("Page{0,number,integer}");
            class_info_table.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_printClassesActionPerformed

    private void search_student_for_markActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_student_for_markActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_student_for_markActionPerformed

    private void search_student_for_markKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_student_for_markKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            // thuc hien tim danh sach lop hoc bang phim ENTER
            if (search_student_for_mark.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Type ID first");
            } else {
                String maSV = search_student_for_mark.getText().toString();
                if (student.check_maSV(maSV)) {
                    opt_studentName__mark.setText(student.getStudentName_bymaSV(maSV));
                } else {
                    JOptionPane.showMessageDialog(this, "Id does not exist");
                    search_student_for_mark.requestFocus();
                }
            }
        }
    }//GEN-LAST:event_search_student_for_markKeyReleased

    private void search_student_for_markKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_search_student_for_markKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_search_student_for_markKeyTyped

    private void btn_find_student_for_markActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_find_student_for_markActionPerformed
        if (search_student_for_mark.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Type ID first");
        } else {
            String maSV = search_student_for_mark.getText().toString();
            if (student.check_maSV(maSV)) {
                opt_studentName__mark.setText(student.getStudentName_bymaSV(maSV));
            } else {
                JOptionPane.showMessageDialog(this, "Id does not exist");
                search_student_for_mark.requestFocus();
            }
        }
    }//GEN-LAST:event_btn_find_student_for_markActionPerformed

    private void btn_clearID__markActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearID__markActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearID__markActionPerformed

    private void btn_printClasses2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printClasses2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_printClasses2ActionPerformed

    private void btn_clearClass_onTable__class2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearClass_onTable__class2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clearClass_onTable__class2ActionPerformed

    private void btn_showMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showMarkActionPerformed
        // Xem diem cua sinh vien
        String maSV = search_student_for_mark.getText();
        String schoolyear = compb_SearchSchoolyear.getSelectedItem().toString();
        int semester = Integer.parseInt(compb_SearchSemester.getSelectedItem().toString());
        mark_info_table.setModel(new DefaultTableModel(null, new Object[]{"Semester", "School Year", "Mark", "Class ID", "Credit", "Class name"}));
        stu_mark.get_mark_by_stuID(mark_info_table, maSV, schoolyear, semester);
        
        double diemTBHk = stu_mark.sum_mark(maSV, schoolyear, semester);
        opt_totalScore.setText(diemTBHk+"");
    }//GEN-LAST:event_btn_showMarkActionPerformed

//    kiem tra thong tin da ton tai chua
    public boolean check_email_exist() {
        int id = Integer.parseInt(ipt_studentID.getText());
        if (!student.isEmailExist(ipt_studentEmail.getText(), id)) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Email address already existed");
        }
        ipt_studentEmail.requestFocus();
        return false;
    }

    public boolean check_phoneNumber_exist() {
        int id = Integer.parseInt(ipt_studentID.getText());
        if (!student.isPhoneNumberExist(ipt_studentPhoneNumber.getText(), id)) {
            return true;
        }
        JOptionPane.showMessageDialog(this, "Phone number already existed");
        ipt_studentPhoneNumber.requestFocus();
        return false;
    }

    public boolean check_ID_exist() {
        if (!student.isIdExist(Integer.parseInt(ipt_studentID.getText()))) {
            return true;
        }
        JOptionPane.showMessageDialog(this, "No already existed");
        ipt_studentID.setText("" + student.getMax());
        return false;
    }    // click vao hang nao thi hang do hien du lieu    // xoa sinh vien

    public boolean check_maSV_exist() {
        int id = Integer.parseInt(ipt_studentID.getText());
        if (!student.isMaSVExist(ipt_maSV.getText(), id)) {
            return true;
        }
        JOptionPane.showMessageDialog(this, "Student ID already existed");
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel Gender1;
    private javax.swing.JLabel Gender4;
    private javax.swing.JLabel Gender5;
    private javax.swing.JButton btn_addStudent;
    private javax.swing.JButton btn_clearClass_onTable__class;
    private javax.swing.JButton btn_clearClass_onTable__class2;
    private javax.swing.JButton btn_clearID__class;
    private javax.swing.JButton btn_clearID__mark;
    private javax.swing.JButton btn_clearSearch;
    private javax.swing.JButton btn_clearStudentInfo;
    private javax.swing.JButton btn_clearStudent_onTable;
    private javax.swing.JButton btn_deleteStudent;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_find_student_for_class;
    private javax.swing.JButton btn_find_student_for_info;
    private javax.swing.JButton btn_find_student_for_mark;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_printClasses;
    private javax.swing.JButton btn_printClasses2;
    private javax.swing.JButton btn_print_students;
    private javax.swing.JButton btn_showMark;
    private javax.swing.JButton btn_show_all_students;
    private javax.swing.JButton btn_updateStudetn;
    private com.toedter.calendar.JDateChooser chose_dateOfBirth;
    private javax.swing.JTable class_info_table;
    private javax.swing.JComboBox<String> compb_SearchSchoolyear;
    private javax.swing.JComboBox<String> compb_SearchSemester;
    private javax.swing.JComboBox<String> compb_gender;
    private javax.swing.JTextField ipt_3;
    private javax.swing.JTextField ipt_maSV;
    private javax.swing.JTextField ipt_studentAddress;
    private javax.swing.JTextField ipt_studentEmail;
    private javax.swing.JTextField ipt_studentID;
    private javax.swing.JTextField ipt_studentName;
    private javax.swing.JTextField ipt_studentPhoneNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable mark_info_table;
    private javax.swing.JTextField opt_studentName__class;
    private javax.swing.JTextField opt_studentName__mark;
    private javax.swing.JTextField opt_totalCredits__class;
    private javax.swing.JTextField opt_totalScore;
    private javax.swing.JTextField search_student_for_class;
    private javax.swing.JTextField search_student_for_info;
    private javax.swing.JTextField search_student_for_mark;
    private javax.swing.JTable student_info_table;
    private javax.swing.JTabbedPane tab_student;
    // End of variables declaration//GEN-END:variables
}
